### ISSUE TITLE
[vite-plugin-components] has naming conflicts with other components, ignored.

### ISSUE THREAD

**Issue by fyeeme** [antfu/vite-plugin-components#103]
```shell
src
--pages
   |- index.vue
--components
----role
      |- List.vue
----user
      |- List.vue
```

1. import `components/user/List.vue`  in ` pages/index.vue`
2. import `components/role/List.vue`  in  `components/user/List.vue`
3.  npm run dev 

then error goes here:
![image](https://user-images.githubusercontent.com/6078758/126193296-62a4e211-3ffa-4fc4-b546-068305c47337.png)

Also, as `components/role/List.vue `  is ignored, so it will not be rendered, 

if file name is naming conflicts,  a good way to solve is do like this:

```js
import RoleList from "src/components/role/List.vue";
```
add folder name as compoent name.

**!important**
**after reading source code, I learned that parse `role/List.vue` as  '\<Role-List/\>`'。Maybe this should be reminded in the documentation**

 repo is here : [https://github.com/fyeeme/vite-plugin-components-demo](https://github.com/fyeeme/vite-plugin-components-demo)

**Comment by acrobat2** [comment]
And what about dynamic imports aka `import('src/components/role/List.vue')` and `<component :is="component" />`?

**Comment by pedropcruz** [comment]
Sorry @fyeeme but didnt get that solution for this. Can you explain how did you solve it?

**Comment by fyeeme** [comment]
@pedropcruz  config is supported for solving this,default is false, you can have a try. 

{
// Allow subdirectories as namespace prefix for components.
  directoryAsNamespace: false,
}

**Comment by hellozhangran** [comment]
> @pedropcruz config is supported for solving this,default is false, you can have a try.
> 
> { // Allow subdirectories as namespace prefix for components. directoryAsNamespace: false, }

i found even added directoryAsNamespace: true, below still warning:


[unplugin-vue-components] component "BarChart"(/overview/components/BarChart.vue) has naming conflicts with other components, ignored.

--- 
i have another component in /dashboard/components/BarChart.vue

**Comment by Shujee** [comment]
I'm getting this issue with nested routes. So if I have `pages/home.vue` and then a folder named `pages/home` and inside that folder I have `pages/home/index.vue`, vite complains:

```
[unplugin-vue-components] component "Home"(/var/www/html/client/src/pages/Home.vue) has naming conflicts with other components, ignored.
```
