### ISSUE TITLE
this plugin destroy sourcemap

### ISSUE THREAD

**Issue by tjx666** [antfu/vite-plugin-components#107]
When using this plugin, I can't normally debugging in chrome. For example, I can't set breakpoint at below position:

![image](https://user-images.githubusercontent.com/41773861/126478620-fb77722c-d43c-45f1-8a86-5ed6ced5258c.png)

After I remove this plugin, eveything goes ok.

reproduce repositiory: https://github.com/tjx666/vite-antv/blob/master/src/App.vue#L20

**Comment by Fallsleep** [comment]
I got the same problem with this plugin, it cause the source map locate at wrong row, if set breakpoint at row 21 or 23, the breakpoint maybe at row 20

**Comment by h4091** [comment]
> When using this plugin, I can't normally debugging in chrome. For example, I can't set breakpoint at below position:
> 
> ![image](https://user-images.githubusercontent.com/41773861/126478620-fb77722c-d43c-45f1-8a86-5ed6ced5258c.png)
> 
> After I remove this plugin, eveything goes ok.
> 
> reproduce repositiory: https://github.com/tjx666/vite-antv/blob/master/src/App.vue#L20

```
      {
        ...Components({
          resolvers: [VantResolver()],
        }),
        enforce: 'post',  // Add
      },
```
This solved my problem
