### ISSUE TITLE
Has any plan to support react components library?

### ISSUE THREAD

**Issue by percy507** [antfu/vite-plugin-components#111]

**Comment by antfu** [comment]
Sorry no

**Comment by percy507** [comment]
@antfu 
Sorry...I misunderstood the usage scene of this plugin.

I only want to find a vite plugin to autoload `antd` style by component just now.
Now i find it. <https://github.com/anncwb/vite-plugin-style-import>

**Comment by uinio** [comment]
@vitejs/plugin-react use babel.config.js
