### ISSUE TITLE
Element-plus dependencies updated, reloading page...

### ISSUE THREAD

**Issue by jayfongs** [antfu/vite-plugin-components#115]
Use vite2.5 + element-plus 1.0.2-beta.71 + vite-plugin-components 0.13.2

The initial run will load multiple times, and the page will refresh multiple times. How to solve this?

![image](https://user-images.githubusercontent.com/17779577/130397030-62cc0230-1260-4236-b636-5f87493ec520.png)

**Comment by antfu** [comment]
https://github.com/antfu/vite-plugin-optimize-persist
