### ISSUE TITLE
Hi, the element-plus has released a new version

### ISSUE THREAD

**Issue by Xwudao** [antfu/vite-plugin-components#117]
and, there are some `Breaking changes`：
https://github.com/element-plus/element-plus/discussions/3020

and, maybe this resovler need change:

https://github.com/antfu/vite-plugin-components/blob/main/src/resolvers/element-plus.ts#L28

**Comment by blooddrunk** [comment]
Seems like they have updated [vite-plugin-element-plus](https://element-plus.org/#/zh-CN/component/quickstart#wo-xiang-tong-shi-an-xu-yin-ru-zu-jian-he-yang-shi-wo-ying-gai-zen-me-zuo) mentioned in their doc to adopt the new change.
