### ISSUE TITLE
ES Destructure import with customResolvers

### ISSUE THREAD

**Issue by SasanFarrokh** [antfu/vite-plugin-components#14]
I saw the new customResolvers feature, it's awesome

Is there a way that we can add a custom resolver for our ui-kit library? something like this:

```js
{
  customResolvers: componentName => {
       return { path: 'bootstrap-vue', import: 'BSelect' }
  }
}
```

and import it like this:

```js
import { BSelect } from 'bootstrap-vue' 
```

Thanks for the great work.

**Comment by antfu** [comment]
Does `bootstrap-vue` support Vue 3? I am happy to support it, can you share with me some Vue 3 compactible UI frameworks for me to do the testing? Thanks.

**Comment by SasanFarrokh** [comment]
No i just suggested an example,

You can just export two different component like this

```js
// My Library
import { h } from 'vue' 

export const SampleComponent = {
    render() {
        h('span', {}, ['Test SampleComponent'])
    }
}

export const NextComponent = {
    render() {
        h('span', {}, ['Test NextComponent'])
    }
}
```

We're writing our own component library, i made some changes to support this.

**Comment by antfu** [comment]
Here you go!
