### ISSUE TITLE
TypeError: Cannot read property 'endsWith' of undefined

### ISSUE THREAD

**Issue by Mehdi-Hp** [antfu/vite-plugin-components#15]
I've added vite-plugin-components to my vite project and it simply throws an error saying:

```
[...]/node_modules/vite-plugin-components/dist/index.js:156
  return reqPath.endsWith(RESOLVER_EXT);
                 ^
TypeError: Cannot read property 'endsWith' of undefined
```

I've casually checked the source code and it seems koa.path is undefined.

**Comment by Mehdi-Hp** [comment]
Also If I change the line to `return reqPath && reqPath.endsWith(RESOLVER_EXT);` I get a new error that says `next()` is not a function`.  
Is this a version problem?

**Comment by naturalethic** [comment]
> Is this a version problem?

Yes.  I believe this only works with Vite 1.x

**Comment by antfu** [comment]
Vite supported from v0.6.x
