### ISSUE TITLE
resolve Record type Alias

### ISSUE THREAD

**Issue by HomyeeKing** [antfu/vite-plugin-components#17]
should we support the **Record type** `alias`?

https://github.com/antfu/vite-plugin-components/blob/893dfa40d5006d6d276f6a2460cd29da9179ddb4/src/utils.ts#L128

**Comment by antfu** [comment]
Sounds reasonable. Wondering if Vite offered an API to handle this. If not, guess it's good to have here. Are you interested in creating a PR? Thanks.

**Comment by HomyeeKing** [comment]
ok, I'll check that

**Comment by HomyeeKing** [comment]
emm.. , I overthink about this because the plugin run after the alias be resolved

so it's right with `ResolvedConfig['alias']` type
