### ISSUE TITLE
Support Vue 2

### ISSUE THREAD

**Issue by pitcher-maarten** [antfu/vite-plugin-components#24]
Just following the docs while using Vue 2.
The plugin recognizes the component path, but doesn't seem to import the components.

`ViteComponents({
      dirs: ['./src/components'],
    })`

`Unknown custom element: <Test> - did you register the component correctly? For recursive components, make sure to provide the "name" option`

```
<template>
    <div>
        test
    </div>
</template>

<script>
    export default {
        name: 'Test'
    }
</script>

<style lang="scss" scoped>

</style>
```

**Comment by antfu** [comment]
Repro please, thanks

**Comment by pitcher-maarten** [comment]
https://glitch.com/edit/#!/vite-issue

**Comment by antfu** [comment]
We didn't design this for Vue 2 and this might not be a high-priority thing to me. If anyone would like to draft a PR to add the support for Vue 2, I am happy to review it. Thanks!

**Comment by Atinux** [comment]
Would be pretty nice @antfu 🔥

**Comment by antfu** [comment]
Alright, I broke my words and now it's here in v0.7.0! With these configurations:

```ts
// vite.config.js
import { createVuePlugin } from 'vite-plugin-vue2'
import ViteComponents from 'vite-plugin-components'

export default {
  plugins: [
    createVuePlugin(),
    ViteComponents({
      transformer: 'vue2', // <--
    }),
  ],
}
```

@Atinux Thanks for the push :P

**Comment by antfu** [comment]
Might have some edge cases that it does not cover tho, if you find any, I am open for contributions :)

**Comment by pitcher-maarten** [comment]
@antfu haha thanks for breaking your words, will tell if any inconveniences.
