### ISSUE TITLE
How to automatically import components on demand from an UI library?

### ISSUE THREAD

**Issue by yangss3** [antfu/vite-plugin-components#26]
If I want to automatically import components on demand from an UI library like **ant-design-vue** or **element-plus** , what should I do? Would you give an example in the document?

**Comment by antfu** [comment]
https://github.com/antfu/vite-plugin-components/blob/4b1a1c99aee04189813733450b038d8693ae6c3b/example/basic/vite.config.ts#L29-L34

**Comment by antfu** [comment]
At the time we support this feature, neither Antd nor ElementPlus is ready for Vue 3 yet. If you figure out a way to support them, feel free to add to this example and I will update the documentation about it. Thanks

**Comment by yangss3** [comment]
Thank you very much for reply!
I just tried the above config on Vant and AntDesignVue, components auto importing on demand are works,  but styles are lose, it seems that have to import the entire styles manually.

**Comment by antfu** [comment]
> but styles are lose, it seems that have to import the entire styles manually.

Yeah, based on how the library made, you will need to follow their instruction for setups other than component importing,

**Comment by develar** [comment]
Example for `element-plus` library:

```ts
      customComponentResolvers: [
        name => {
          if (name.startsWith("El")) {
            return {
              path: `element-plus/es/el-${name[2].toLowerCase()}${name.substring(3).replace(/[A-Z]/g, l => `-${l.toLowerCase()}`)}`,
            }
          }
          return null
        },
      ],
```

**Comment by antfu** [comment]
@develar Thanks a lot! I will make them built-in for people to use directly.

@yangss3 I would be grateful if you would like to share your configure for antdv as well :)

**Comment by yangss3** [comment]
I tried for antdv with a configuration similar to which you post for vant:
```js
(name: string) => {
    if (name.startsWith('A'))
        return { importName: name.slice(1), path: 'ant-design-vue/es' }
    },
```
 but it works not so nice,  except the style losing issue, only part of components can be import correctly. I checked the component directory structure of antdv,  not like vant defines each component in its own directory, antdv puts those relational componets(etc. Form and FormItem, Input and Textarea) into the same dirctory，so for these components auto import will be failed.

**Comment by antfu** [comment]
Now we have resolvers for these libraries built-in for people to use since 0.8.0, thank you all!
https://github.com/antfu/vite-plugin-components#importing-from-ui-libraries

**Comment by eivmosn** [comment]
> Now we have resolvers for these libraries built-in for people to use since 0.8.0, thank you all!
> https://github.com/antfu/vite-plugin-components#importing-from-ui-libraries

I tried AntDesignVueResolver but css is not auto inject or onload , here is my code 

//vite.config.ts

import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import ViteComponents, { AntDesignVueResolver } from 'vite-plugin-components'

export default defineConfig({
  plugins: [
    vue(),
    ViteComponents({
      globalComponentsDeclaration: true,
      customComponentResolvers: [
        AntDesignVueResolver({
          importStyle: 'less'
        }),
      ]
    }),
  ]
})
