### ISSUE TITLE
DirectoryAsNamespace doesnt work as intended!

### ISSUE THREAD

**Issue by Subwaytime** [antfu/vite-plugin-components#27]
Hey there,
so i just recently updated to the latest Version of `vite-plugin-components` (0.7.3) and `directoryAsNamespace` doesnt work anymore.

Expected:
`ui/navigation.vue` --> `ui-navigation.vue`

Current Output:
`ui/navigation.vue` --> `navigation.vue`

Test Repo will follow soon!

**Comment by Subwaytime** [comment]
https://github.com/Subwaytime/vite-plugin-components-issue

It seems there is also an Issue that `node_modules` dont get installed after installing `vite-plugin-components`.
Thats why his error occurs `Error: Cannot find module 'fast-glob'`

**Comment by antfu** [comment]
Looks like a Windows-specific problem. I have added some tests for it and should be fixed in 0.7.4.

**Comment by Rasool-deldar** [comment]
d
