### ISSUE TITLE
Support SourceMap for transformation

### ISSUE THREAD

**Issue by ChasLui** [antfu/vite-plugin-components#33]

**Comment by antfu** [comment]
I don't use source map myself so this is kinda a low priority to me. While this should not be hard using [`magic-string`](https://github.com/Rich-Harris/magic-string), open for contributions if anyone really need that. Thanks

**Comment by raphaelsaunier** [comment]
Thanks so much for fixing this regardless! @antfu 🙏 

Not a heavy user of soucemaps either, but it feels good to no longer see a wall of with a 100+ `Sourcemap is likely to be incorrect: a plugin (vite-plugin-components) was used to transform files, but didn't generate a sourcemap for the transformation. Consult the plugin documentation for help` warnings when building an app.
