### ISSUE TITLE
customComponentResolvers  AntDesignVueResolver error

### ISSUE THREAD

**Issue by nshusr** [antfu/vite-plugin-components#35]
use vite config customComponentResolvers

``` sh
Uncaught SyntaxError: The requested module '/node_modules/.vite/ant-design-vue_es.js?v=8f1bc1f8' does not provide an export named 'MenuItem'
```

**Comment by nshusr** [comment]
https://github.com/vueComponent/ant-design-vue/blob/next/components/index.ts#L73

ant-design-vue/es no export MenuItem... only Menu

MenuItem, SubMenu, ItemGroup, is Component in Menu

**Comment by antfu** [comment]
I don't use Antv myself, would be appreciated if someone could sort this out and send a PR. Thanks!

**Comment by tangjinzhou** [comment]
please update to beta.6 @nshusr

**Comment by nabaonan** [comment]
> please update to beta.6 @nshusr

刚试了一下，使用vite-plugin-components的AntDesignVueResolver，加载之后是没有样式的，能不能把样式像components.js一样导出，按需引入样式，现在只能自定义成这个写法，
```typescript
  else if (name.match(/^A[A-Z]/)) {
            //ant-design-vue

            const importName = name.slice(1);
            return {
              importName: importName,
              path: `ant-design-vue/es`,
              sideEffects: "ant-design-vue/es/style",
            };
          }

```

好像是全量引入了样式 @tangjinzhou
