### ISSUE TITLE
can this plugin solve the problem of importing vue file without using suffix '*.vue'

### ISSUE THREAD

**Issue by williamyorkl** [antfu/vite-plugin-components#42]
hi, as I am aware that when using vite, it needs to add the '*.vue' suffix in every file, but now I am doing a update job from webpack4 to vite, so a great amount of vue files lacking of '*.vue' suffix,which is impossible to fix them manually..... can this plugin do this job ? thanks !

**Comment by antfu** [comment]
https://github.com/antfu/vite-plugin-components#configuration

```ts
ViteComponents({
  // valid file extensions for components.
  extensions: ['vue', 'js', 'jsx', 'ts', 'tsx'],
})
```

?

**Comment by williamyorkl** [comment]
@antfu by doing what you show above, can I write like this when I  import vue component in another vue file ? 
```
import ComponentA from '@/components/ComponentA'  // without indicating it as ComponentA.vue
```

... but I've tried and it doesn't seem working tho

**Comment by antfu** [comment]
No. The `.vue` in importing is required for both Vue 3 and Vite, and I don't think there is a workaround. And it's out-of-scope of this plugin. Closing.
