### ISSUE TITLE
VuetifyResolver remove sass warnings

### ISSUE THREAD

**Issue by Olyno** [antfu/vite-plugin-components#48]
Hi 👋🏻 

I'm not sure if this problem is related to ``vite-plugin-components`` or ``vuetify`` directly, but when I start the dev server of ``vite``, I get this warning for each components of Vuetify:

```
   ╷
62 │     'sm': $grid-gutter / 6,
   │           ^^^^^^^^^^^^^^^^
   ╵
    node_modules/vuetify/src/styles/settings/_variables.scss 62:11     @import
    node_modules/vuetify/src/styles/settings/_index.sass 1:9           @import
    node_modules/vuetify/src/styles/styles.sass 2:9                    @import
    node_modules/vuetify/src/components/VTreeview/_variables.scss 1:9  @import
    node_modules/vuetify/src/components/VTreeview/VTreeview.sass 1:9   root stylesheet

DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($grid-gutter, 3)
```

I find them annoying. Is there any way to hidde them or remove them?

**Comment by hannoeru** [comment]
https://github.com/vuetifyjs/vuetify/issues/13694

Use sass < 1.33 as workaround

**Comment by Olyno** [comment]
Nice thanks you 😃

**Comment by stranavad** [comment]
And if I need math.div which is not in <1.33?

**Comment by wJoenn** [comment]
@stranavad Why can't you use `calc($grid-gutter / 3)` instead ?
`calc` is part of vanilla css so there shouldn't be anything preventing you from using it
