### ISSUE TITLE
bug: globalComponentsDeclaration doesn't work with pnpm workspaces

### ISSUE THREAD

**Issue by Async0x42** [antfu/vite-plugin-components#49]
TypeScript with globalComponentsDeclaration doesn't generate components.d.ts when using pnpm and workspaces in the attached image's folder structure.

If I separate it to a regular folder with just the client application, then it is generated correctly.

![image](https://user-images.githubusercontent.com/3268854/120054362-986f6380-bffd-11eb-8fe8-ca4f7c40c050.png)

**Comment by antfu** [comment]
Not sure if I got it, can you provide more context?

**Comment by Async0x42** [comment]
Ah, please disregard this issue. I'm not sure what the problem was, but it's now working for me with the pnpm workspaces. Thanks for this plugin, it's great.

I can create a new issue, but the generated components.d.ts has incorrect paths on my Windows system:

![image](https://user-images.githubusercontent.com/3268854/120054763-ee450b00-bfff-11eb-96d4-2b0ec1c7a24b.png)

If I change all '\' to '/' then it works correctly with TypeScript definitions

**Comment by antfu** [comment]
Fixed, thanks
