### ISSUE TITLE
Support mounting app via new Vue({el: "#app"})

### ISSUE THREAD

**Issue by chasegiunta** [antfu/vite-plugin-components#51]
Potentially to #34 (needs `alias: { vue: require.resolve("vue/dist/vue.esm.js") }`)

Two ways to init (Vue 2):
```
// App.vue
const app = createApp({
  render: () => h(App),
});
```

```
// No App.vue — init on #app el
 var app = new Vue({
   el: "#app",
});
```

The latter will fail to register/find components.
If this is expected behavior, forgive me and close, but took me embarrassingly long to troubleshoot. 

Hopefully this scenario can be supported. If a minimal codesandbox is needed, let me know.

**Comment by antfu** [comment]
Sorry, this feature only works for Vue SFC, and I don't really see it's feasible for inline components.

**Comment by chasegiunta** [comment]
@antfu technically, all the _components_ **are** SFC, but the app itself is initialized onto the #app element. This scenario let's everyone doing backend integration (Laravel, Rails) to still use backend templates, while also pulling in SFCs (and slotting content into them). 

If it was possible to slot `<App>` that would be nice, but unfortunately you can't, thus inlining for `app` is required and we can use SFCs everywhere else.

**Comment by antfu** [comment]
This plugin is relaying on `.vue` SFC's compile result and transform it to support auto importing (eg. `__resolveComponent('Foo')` will be resolved to `import Foo from './components/Foo.vue'` and replace the usage to `Foo`. If you can find a solution to your cases I am happy to review the PR.
