### ISSUE TITLE
Can't make type check for props work for global components with volar

### ISSUE THREAD

**Issue by xorik** [antfu/vite-plugin-components#52]
[Demo project](https://github.com/xorik/vite-global-typing)

Hi! I've created a fresh vite app with this plugin, added `globalComponentsDeclaration: true`.
The file `components.d.ts` is generated, but vscode doesn't show me warnings of incorrect using of props, unless I import the component.

Button.vue:
```vue
<script setup lang="ts">
import { defineProps } from 'vue'

const props = defineProps({
  size: {
    type: String,
    required: true,
  },
})
</script>
```

Component is not imported (no type checks for props)
<img width="579" alt="Screen Shot 2021-05-31 at 20 26 19" src="https://user-images.githubusercontent.com/347044/120229905-77ea1800-c24e-11eb-82e4-8e0715ef7735.png">

Component is imported, so type check works great.
<img width="801" alt="Screen Shot 2021-05-31 at 20 27 13" src="https://user-images.githubusercontent.com/347044/120229954-96e8aa00-c24e-11eb-9819-fb5640c69d19.png">

I'm expecting to see something like that: https://twitter.com/antfu7/status/1397168229005463563 but can't figure out what's wrong.

And what's more strange, this feature is working perfectly if I install a new vitesse project.

**Comment by antfu** [comment]
You will need to remove the vue shim as Volar will handle it https://github.com/xorik/vite-global-typing/blob/main/src/shims-vue.d.ts

**Comment by xorik** [comment]
@antfu removed, still doesn't seem to work 😞 Probably some other package in node_modules adds own types that interfere with volar

**Comment by antfu** [comment]
Enabled Volar TS Plugin?

**Comment by xorik** [comment]
Yes, plugin is on. I will try to compare libraries between this and vitesse, probably some package is messing with type definitions.
https://user-images.githubusercontent.com/347044/120286326-68a2b300-c2be-11eb-8639-eab9dc08501a.mov

**Comment by xorik** [comment]
@antfu found the issue:
By default vite have tsconfi.json:
```
  "include": [
    "src/**/*.ts",
    "src/**/*.d.ts",
    "src/**/*.tsx",
    "src/**/*.vue",
  ]
```

So file `components.d.ts` is not included. Vitesse in the other hand doesn't have `include`, only `exclude` in the config.

Probably it makes sense to add it to readme, so other people won't get confused.
