### ISSUE TITLE
Conflict with vite-plugin-vue2 when sourcemap enabled 

### ISSUE THREAD

**Issue by Djaler** [antfu/vite-plugin-components#53]
If I enable sourcemap in vite config (`build.sourceMap: true`), then I'll get this strange error:
`[vite] Internal server error: ENOENT: no such file or directory, open '/home/kromanov/Playground/vite-example/src/components/HelloWorld.vue?vue&type=style&index=0&scoped=true&lang.css'`

Here you can check reproduction of the bug.
Try to do `npm run dev`, you'll see error.
Then disable sourcemap in vite config and run again. Error will gone.
https://github.com/Djaler/vite-vue2-components-sourcemap-bug

**Comment by antfu** [comment]
`vite-plugin-vue2` does not generate sourcemap

**Comment by Djaler** [comment]
So what is this about https://github.com/underfin/vite-plugin-vue2/commit/1e0398323e62264ab374352d6a41282d5be23f73?

**Comment by antfu** [comment]
Good to know it's supported 2 days ago. But this are likely to be a bug of their source generation as it works fine on Vue 3. Keep track on https://github.com/underfin/vite-plugin-vue2/issues/90

**Comment by Djaler** [comment]
Ok, thanks
