### ISSUE TITLE
Why component inside component not automatically loaded?

### ISSUE THREAD

**Issue by ngekoding** [antfu/vite-plugin-components#55]
After solving the issue about [How to configure for Element UI?](https://github.com/antfu/vite-plugin-components/issues/54), I get a new problem.

This is about, when using Element UI, there is a component inside a component, and this library not automatically loaded it. For example, inside the `menu-item` component there is `tooltip` component, which is used/showed when the menu collapsed.

Here the example when I use `menu-item` component without manually imported the `tooltip` component.

<img width="498" alt="Tooltip problem" src="https://user-images.githubusercontent.com/11625690/120440863-92d79c00-c3b6-11eb-99b6-fbb906f308f3.png">

And here the example when I try to use `tooltip` on the same page (actually I don't need it in this page).

<img width="435" alt="Manually import tooltip" src="https://user-images.githubusercontent.com/11625690/120440951-a84cc600-c3b6-11eb-8bec-54a977985bb8.png">

And here is the `menu-item` code looks like, that using el-tooltip component.

<img width="1206" alt="menu-item component" src="https://user-images.githubusercontent.com/11625690/120441591-4e003500-c3b7-11eb-80aa-23d2de83305c.png">

**So, how can we solve this problem?**

I think this is about recursive component import.

Thanks in advance.

**Comment by nabaonan** [comment]
This is element-plus's bug, try the latest version 


Here is element plus issue link

[issue link](https://github.com/element-plus/element-plus/issues/2423)

**Comment by ngekoding** [comment]
> This is element-plus's bug, try the latest version
> 
> Here is element plus issue link
> 
> [issue link](https://github.com/element-plus/element-plus/issues/2423)

I used Element UI for Vue 2, not Element Plus

**Comment by nabaonan** [comment]
> > This is element-plus's bug, try the latest version
> > Here is element plus issue link
> > [issue link](https://github.com/element-plus/element-plus/issues/2423)
> 
> I used Element UI for Vue 2, not Element Plus

ElementUI has the same problem
![image](https://user-images.githubusercontent.com/17247526/124611267-db95df80-dea3-11eb-943c-a0debb3437be.png)

**Comment by ngekoding** [comment]
@nabaonan The fixed version only for Element Plus right? I checked that ElementUI still missing that import.

**Comment by antfu** [comment]
Close as this is an upstream issue, please track there
