### ISSUE TITLE
[Q&A]ant-design-vue with AntDesignVueResolver:unknown theme, type: undefined, name: undefined'

### ISSUE THREAD

**Issue by abear-eatsfish** [antfu/vite-plugin-components#65]
> Vue2.x + Vite2.0 + ant-design-vue1.7.5

中文：
当我使用Ant-Design-Vue（"ant-design-vue": "^1.7.5",）的时候
`import ViteComponents, { AntDesignVueResolver } from "vite-plugin-components";`
提示这样的报错，这个是否是Antd自身的问题？有解决方案吗？在其他也找过相关问题，但是没找到解决方案（顺便说下：新人小白，所以这个问题也许会浪费时间）

___
MT(machine translation)

When I use ant design Vue`"ant-design-vue": "^1.7.5",`
`import ViteComponents, { AntDesignVueResolver } from "vite-plugin-components";`
Prompt such an error. Is this the problem of antd itself? Is there a solution? I've found related problems in other places, but I haven't found a solution (btw: Newcomer,so this problem may be a waste of time)

---

Error Info:
```
utils.js:105 Uncaught TypeError: Unknown theme type: undefined, name: undefined
    at withSuffix (utils.js:105)
    at Icon.js:25
    at Array.forEach (<anonymous>)
    at Object.add (Icon.js:24)
    at index.js:18
```

vite.config.js
```
import ViteComponents, { AntDesignVueResolver } from "vite-plugin-components";

const config = defineConfig({
  plugins: [
    ViteComponents({
      customComponentResolvers: [
        AntDesignVueResolver(),
        ViteIconsResolver({
          componentPrefix: "",
        })
      ],
    }),
    // ViteIcons({
    //   defaultStyle: "",
    // }),
    // WindiCSS(),
  ],
});
```

**Comment by tangjinzhou** [comment]
Ant 1.7 version is not friendly to vite support
It is recommended to use ant 2.x version

**Comment by abear-eatsfish** [comment]
> Ant 1.7 version is not friendly to vite support
> It is recommended to use ant 2.x version

For project reasons, I need to support IE11, Vue3.0 has not found a way to support IE11 for the time being, so I only use other tools temporarily and use vite later
