### ISSUE TITLE
ElementPlusResolver(), error

### ISSUE THREAD

**Issue by Fanna1119** [antfu/vite-plugin-components#68]
using element gives the following errors

`GET http://localhost:3333/@id/@vite-icons/el/button net::ERR_ABORTED 404 (Not Found)
vue-router.esm-bundler.js:72 [Vue Router warn]: uncaught error during route navigation:
warn @ vue-router.esm-bundler.js:72
triggerError @ vue-router.esm-bundler.js:3240
(anonymous) @ vue-router.esm-bundler.js:2977
Promise.catch (async)
pushWithRedirect @ vue-router.esm-bundler.js:2974
push @ vue-router.esm-bundler.js:2909
install @ vue-router.esm-bundler.js:3323
use @ runtime-core.esm-bundler.js:4001
createApp2 @ index.mjs:34
(anonymous) @ index.mjs:63
ViteSSG @ index.mjs:65
(anonymous) @ main.ts:12
vue-router.esm-bundler.js:3242 TypeError: Failed to fetch dynamically imported module: http://localhost:3333/src/layouts/404.vue?t=1624293178771
triggerError @ vue-router.esm-bundler.js:3242
(anonymous) @ vue-router.esm-bundler.js:2977
Promise.catch (async)
pushWithRedirect @ vue-router.esm-bundler.js:2974
push @ vue-router.esm-bundler.js:2909
install @ vue-router.esm-bundler.js:3323
use @ runtime-core.esm-bundler.js:4001
createApp2 @ index.mjs:34
(anonymous) @ index.mjs:63
ViteSSG @ index.mjs:65
(anonymous) @ main.ts:12
vue-router.esm-bundler.js:72 [Vue Router warn]: Unexpected error when starting the router: TypeError: Failed to fetch dynamically imported module: http://localhost:3333/src/layouts/404.vue?t=1624293178771
warn @ vue-router.esm-bundler.js:72
(anonymous) @ vue-router.esm-bundler.js:3325
Promise.catch (async)
install @ vue-router.esm-bundler.js:3323
use @ runtime-core.esm-bundler.js:4001
createApp2 @ index.mjs:34
(anonymous) @ index.mjs:63
ViteSSG @ index.mjs:65
(anonymous) @ main.ts:12
ssss:1 Uncaught (in promise) TypeError: Failed to fetch dynamically imported module: http://localhost:3333/src/layouts/404.vue?t=1624293178771
Promise.then (async)
install @ pwa.ts:8
(anonymous) @ main.ts:17
(anonymous) @ main.ts:17
createApp2 @ index.mjs:40
(anonymous) @ index.mjs:63
ViteSSG @ index.mjs:65
(anonymous) @ main.ts:12
index.mjs:65 Uncaught (in promise) TypeError: Failed to fetch dynamically imported module: http://localhost:3333/src/layouts/404.vue?t=1624293178771`

**Comment by antfu** [comment]
Can't help without a repro and more info.
