### ISSUE TITLE
Error when using recursive component

### ISSUE THREAD

**Issue by jacobclevenger** [antfu/vite-plugin-components#7]
When attempting to use a recursive component the plugin breaks.

![image](https://user-images.githubusercontent.com/7064956/91511962-e3155100-e8ae-11ea-9e36-52933a620b23.png)

Minimal reproduction: https://github.com/jacobclevenger/vite-plugin-components-recursion-bug

**Comment by jacobclevenger** [comment]
A temporary work around is to register the same component under a different name and use that name in the template. If you were to modify the repo I attached, you can change these files to get it working

**RecursiveComponent.vue**
```html
<template>
  <div>
    <div>{{data.label}}</div>
    <div class="child">
      <recursive-component-clone v-for="item in data.children" :data="item" />
    </div>
  </div>
</template>

<script lang="ts" setup>
export default {
  name: "RecursiveComponent",
  props: {
    data: Object,
  },
};
</script>
```
And then register that component in your main script

**main.js**
```js
import { createApp } from 'vue'
import App from './App.vue'
import './index.css'

import RecursiveComponent from './components/RecursiveComponent.vue';

createApp(App)
    .component('RecursiveComponentClone', RecursiveComponent)
    .mount('#app')

```

**Comment by antfu** [comment]
Should be fixed in 0.2.11. Please give a try.

**Comment by jacobclevenger** [comment]
Yep works now, thanks for the quick fix! Thought I should mention that it now seems to long components that it registers, not sure if this is intentional

![image](https://user-images.githubusercontent.com/7064956/91514669-528e3f00-e8b5-11ea-99e3-e616b701eb23.png)

**Comment by antfu** [comment]
Ah, sorry about that, work on it

**Comment by antfu** [comment]
Removed in 0.2.12. Thanks

**Comment by jacobclevenger** [comment]
No problem, thanks for the awesome plugin 😄

**Comment by mubaidr** [comment]
While this runs fine, typescript complains about the type of self referencing component:

```bash
'default' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.ts(7022)
```

Using latest `Typescript`, `VsCode` and `Volar` versions. 

Any help would be appreciated.
