### ISSUE TITLE
ant-design-vue ^2.2.0-beta.5 version vite-plugin-components ^0.11.2 Cannot find the name LayoutSider  Export error

### ISSUE THREAD

**Issue by zs-g** [antfu/vite-plugin-components#72]
import ViteComponents, { AntDesignVueResolver } from 'vite-plugin-components'

plugins: [ 
    ViteComponents({customComponentResolvers: [AntDesignVueResolver()] }) 
]
Error message：Uncaught SyntaxError: The requested module '/node_modules/.vite/ant-design-vue_es.js?v=58a06493' does not provide an export named 'LayoutSider'

![1](https://user-images.githubusercontent.com/46895375/123361097-08dbb700-d5a1-11eb-8cf5-57d08525c74c.jpg)
![2](https://user-images.githubusercontent.com/46895375/123361099-0a0ce400-d5a1-11eb-9358-258d0db87344.jpg)
![3](https://user-images.githubusercontent.com/46895375/123361101-0aa57a80-d5a1-11eb-8ae6-ed8b26b45c3a.jpg)

**Comment by tangjinzhou** [comment]
please update to beta.6
