### ISSUE TITLE
tsx not work load style

### ISSUE THREAD

**Issue by uinio** [antfu/vite-plugin-components#73]
```ts
import { defineConfig } from 'vite';
import { resolve } from 'path';
import Vue from '@vitejs/plugin-vue';
import VueJsx from '@vitejs/plugin-vue-jsx';
import ViteComponents, { AntDesignVueResolver } from 'vite-plugin-components';

export default defineConfig({
  resolve: {
    alias: [
      {
        find: '@',
        replacement: resolve(__dirname, 'src'),
      },
    ],
  },
  plugins: [
    Vue(),
    VueJsx(),
    ViteComponents({
      deep: true,
      dirs: ['src'],
      extensions: ['vue', 'tsx'],
      customComponentResolvers: [AntDesignVueResolver()],
    }),
  ],
  css: {
    preprocessorOptions: {
      less: {
        javascriptEnabled: true,
      },
    },
    modules: {
      localsConvention: 'camelCase',
    },
  },
});
```

**Comment by antfu** [comment]
More context? But honestly saying, I don't think you need this plugin for you use tsx exclusively.

**Comment by uinio** [comment]
No more, only these

**Comment by antfu** [comment]
Yeah, then that will be out-of-scope of this plugin.

**Comment by sky124380729** [comment]
> Yeah, then that will be out-of-scope of this plugin.
I think it's necessary. Will you support it in the future?

**Comment by a382775086** [comment]
So，is it the reason why these custom component with tsx doesn't work in prod mode? It's normally in dev.I need 
![image](https://github.com/antfu/unplugin-vue-components/assets/33515710/c2787123-110c-442b-b6d7-9dd392aeb620)
![1691495162314](https://github.com/antfu/unplugin-vue-components/assets/33515710/7f6d27ef-c722-43b2-b235-05e8c30558e7)
