### ISSUE TITLE
The built-in AntDesignVueResolver method cannot load ant design vue component styles on demand

### ISSUE THREAD

**Issue by zs-g** [antfu/vite-plugin-components#79]
Directly use AntDesignVueResolver to load components on demand but fail to load styles

Use this method to : 
import ViteComponents  from 'vite-plugin-components'

plugins:[
  ViteComponents({customComponentResolvers: [
      (name: string) => {
        if(name.match(/^A[A-Z]/)) return {
          importName: name.slice(1),
          path: 'ant-design-vue/es',
          sideEffects: "ant-design-vue/es/style",
        }
      }
    ]})
]

I hope the author can check if there are health problems when building AntDesignVueResolver

![1624864139(1)](https://user-images.githubusercontent.com/46895375/123594882-cfb27980-d822-11eb-9719-b8936ac4e50d.jpg)

**Comment by nabaonan** [comment]
#78 here is my PR
