### ISSUE TITLE
HMR on auto-imported component

### ISSUE THREAD

**Issue by rafaelytakei** [antfu/vite-plugin-components#86]
Hi, it's my first trying to use Vite, so I might be doing something wrong, but here's my problem:

HMR is not working properly on auto imported components using this plugin - if I import them manually it works just fine.

Example repo: https://github.com/rafaelytakei/vite-component-test

On this repo, if you install -> run dev server -> try to change something in the HelloWorld component, it won't update unless I shut down the dev server and start it again. If I import the component manually on pages/index.vue, it updates normally

**Comment by husayt** [comment]
İ have also noticed this problem in 0.12.0. Works in 0.11.5

**Comment by rafaelytakei** [comment]
Just tried downgrading to v0.11.0 and now it's working (v0.11.5 didn't work for me tho)

**Comment by oseau** [comment]
> Just tried downgrading to v0.11.0 and now it's working (v0.11.5 didn't work for me tho)

In my case 0.11.4 is working fine.

**Comment by hannoeru** [comment]
What OS are you using?
