### ISSUE TITLE
SVGs as a component

### ISSUE THREAD

**Issue by sibbng** [antfu/vite-plugin-components#9]
Is this library can register SVGs as a component?

For example `HomeIcon.svg` will be used as `<HomeIcon />` in template.

**Comment by antfu** [comment]
Not sure tho, but maybe you can combine it with https://github.com/visualfanatic/vite-plugin-svg and the following config

```js
ViteComponents({
  extensions: ['vue', 'svg'],
})
```

Hope to hear good news from you :P

**Comment by sibbng** [comment]
Hi @antfu 

Current beta version of https://github.com/visualfanatic/vite-svg/tree/master/packages/vite-plugin-vue-svg with following config makes possible this use case.

```ts
plugins: [
    vue(),
    vueSvgPlugin({defaultExport: 'component'}),
    ViteComponents({
      extensions: ['vue', 'svg'],
    }),
  ],
```

But I didn't figure out how to configure vite-plugin-components for using it without changing defaultExport setting while that plugin support importing SVGs as component by adding ?component query. That seems like what you suggested in https://github.com/visualfanatic/vite-svg/issues/14

**Comment by antfu** [comment]
In v0.7.3

```ts
  plugins: [
    vue(),
    vueSvgPlugin(),
    ViteComponents({
      extensions: ['vue', 'svg'],
      importPathTransform: path => path.endsWith('.svg') ? `${path}?component` : undefined,
    }),
  ],
```
