### ISSUE TITLE
Resolver for Tailwind UI

### ISSUE THREAD

**Issue by develar** [antfu/vite-plugin-components#93]
Resolver for [Tailwind UI](https://tailwindui.com).

Example:

```
        name => {
          if (name.endsWith("Icon")) {
            return {
              path: `@heroicons/vue/outline/esm/${name}.js`,
            }
          }
          else if (name !== "RouterView") {
            return {
              importName: name,
              path: "@headlessui/vue",
            }
          }
          else {
            return null
          }
        },
```

Why it is not easy to enable this resolver by default:
 * Tailwind UI doesn't have prefixes like `el-` (Element Plus) or `a-` (Ant Design View). For now I simply excluded `RouterView` (vue `router-view`). You can see example code — https://tailwindui.com/components/application-ui/application-shells/stacked Simply used as `Menu`, `Disclosure`. Probably we can easily add known list of Tailwind UI component list.
 * For icons `outline` is used (https://heroicons.com) by default. Maybe prefix `Solid` can be added.

Sorry that this issue will be opened for a while in your repository, but I am not ready yet to provide a solid pull request. Still, l want to make Vite awesome and provide possible support of Tailwind UI if someone will search for it :)

**Comment by antfu** [comment]
Isn't Tailwind UI simply a HTML template? If you mean headless ui I think we already have it.
https://github.com/antfu/vite-plugin-components/blob/main/src/resolvers/headless-ui.ts

**Comment by develar** [comment]
Hmm... indeed, thanks, so, only resolver for icons is required.

**Comment by antfu** [comment]
I would recommend https://github.com/antfu/vite-plugin-icons for icons
