### ISSUE TITLE
Code Splitting Documentation

### ISSUE THREAD

**Issue by dougalg** [antfu/vite-plugin-components#99]
Hi thanks for the very cool project!

The documentation says that code splitting is supported, but I don't see any information on the mechanisms to achieve that. Can you point me to an example somewhere if one exists, or maybe explain it a bit?

Sorry if I missed any existing documentation!

**Comment by antfu** [comment]
https://github.com/antfu/vite-plugin-components/issues/46#issuecomment-876272319

**Comment by dougalg** [comment]
@antfu, I see! Thank you for the clarification :)
